Workout 1
================
Jacob Yeung

The 2016 season for the Golden State Warriors stars Stephen Curry, Andre
Iguodala, Kevin Durant, Klay Thompson, and Draymond Green was filled
with excitement. In this report, we analyze the scoring patterns of the
aforementioned Golden State Warriors.

In the 2016 season, Kevin Durant led the Golden State Warriors in
percentage of shots made, successfully scoring over 54% of shots he took
this season. (We include both 2 and 3 point field goals in the total
percentage of shots made). However, Durant only made a total of 495
shots whereas star Stephen Curry made a total of 584 shots. Out of these
584 successful shots, Stephen Curry successfully made 280 3 point field
goals. This means Curry has averaged almost 41% of 3 point field goals.
While Curry successfully made the most 3 point field goals, Klay
Thompson has the highest percentage of successful 3 point field goals,
at over 42%, as well as the second most number of 3 point field goals
made, at 246. Andre Iguodala leads the percentage of 2 point field goals
made at a whopping 63%, shooting 134 2 point field goals successfully.
However, despite his high 2 point field goal success percentage, 2 point
field goal success percentage followup Kevin Durant made 390 2 point
field goals. As we can see, field goal shot success percentage is not
the only factor to keep in mind, as Kevin Durant scores nearly 3 times
as many 2 point field goals as Andre Iguodala while trailing in
percentage of successful 2 point field goals. The rest of the data about
effective shooting percentages is shown in the table below.

Overall Percentages of Successful Field Goals

    ##             name total made perc_made
    ## 4   Kevin Durant   915  495 0.5409836
    ## 2 Andre Iguodala   371  192 0.5175202
    ## 5  Klay Thompson  1220  575 0.4713115
    ## 1  Stephen Curry  1250  584 0.4672000
    ## 3 Draymond Green   578  245 0.4238754

Overall Percentages of Successful 2 Point Field Goals

    ##             name total made perc_made
    ## 2 Andre Iguodala   210  134 0.6380952
    ## 4   Kevin Durant   643  390 0.6065319
    ## 1  Stephen Curry   563  304 0.5399645
    ## 5  Klay Thompson   640  329 0.5140625
    ## 3 Draymond Green   346  171 0.4942197

Overall Percentages of Successful 3 Point Field Goals

    ##             name total made perc_made
    ## 5  Klay Thompson   580  246 0.4241379
    ## 1  Stephen Curry   687  280 0.4075691
    ## 4   Kevin Durant   272  105 0.3860294
    ## 2 Andre Iguodala   161   58 0.3602484
    ## 3 Draymond Green   232   74 0.3189655

Next we look at the shooting charts of the five aforementioned NBA
players.

<img src="../images/gsw-shot-charts.png" style="display: block; margin: auto;" />

As we can see, Klay Thompson and Stephen Curry have a wide range of
position from where they took field goal shots. In addition, Klay
Thompson and Stephen Curry both have many taken many shots, contrasted
with Andre Iguodala’s sparser dotted chart. This also emphasizes that we
cannot only look at one aspect of player performance - Andre Iguodala
has a very high successful shot percentage, yet has scored far fewer
goals than Kevin Durant.

Above we mentioned Iguodala’s scoring percentage and fewer goals scored.
On the other hand, Kevin Durant has taken 915 total shots whereas
Iguodala has only taken 371 total shots. This explains why Kevin Durant
has made double (915) the amount of total goals Iguodala has made (192).
In conclusion, we should keep in mind that when analyzing basketball
players, we should consider a wide range of aspects of their
performance.
